# Generated by Django 5.0.7 on 2024-10-05 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('focus_time_min', models.IntegerField(default=25)),
                ('focus_time_sec', models.IntegerField(default=0)),
                ('short_break_min', models.IntegerField(default=5)),
                ('short_break_sec', models.IntegerField(default=0)),
                ('long_break_min', models.IntegerField(default=15)),
                ('long_break_sec', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
